### ISSUE TITLE
Move covidhm_dsl_v3_paper folder

### ISSUE THREAD

**Issue by theonesp** [theonesp/covidhm-code#3]
the folder CovidHM_DSL_V3 should not exist, [buildcovidhm](https://github.com/theonesp/covidhm-code/tree/master/CovidHM_V3-code/CovidHM_DSL_V3/buildcovidhm)
 & [covidhm_dsl_v3_paper](https://github.com/theonesp/covidhm-code/tree/master/CovidHM_V3-code/CovidHM_DSL_V3/covidhm_dsl_v3_paper) should be inside CovidHM_V3-code as we did in [CovidHM_V2-code](https://github.com/theonesp/covidhm-code/tree/master/CovidHM_V2-code)

**Comment by jefevi** [comment]
Folders re-organized.

Please review and let me know if issue can be closed.
